<a href="https://colab.research.google.com/github/sababatamanna/ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

2.0.2


In [ ]:
my_list =[1,2,3,4]
print(my_list)

[1, 2, 3, 4]


In [ ]:
array=np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [ ]:
print(type(array))

<class 'numpy.ndarray'>


In [ ]:
array= array *2
print(array)

[ 8 16 24 32]


In [ ]:
array = np.array('A')
print(array.ndim)

0


In [ ]:
array = np.array([['A','B','C'],['D','E','F'],['n','m','o']])
print(array.ndim)

2


In [ ]:
print(array.shape)

(3, 3)


In [ ]:
from time import process_time
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0006892059999998867


In [ ]:
import numpy as np
from time import process_time
np_array=np.array([i for i in range(10000)])
start_time=process_time()
python_list=np_array+5
end_time=process_time()
print(end_time-start_time)

NameError: name 'np' is not defined

In [ ]:
import numpy as np
b= np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c=np.array([(1,2,3),(5,6,7)],dtype=float)
print(c)

[[1. 2. 3.]
 [5. 6. 7.]]


In [ ]:
x=np.zeros((4,5))

In [ ]:
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y=np.ones((3,3))

In [ ]:
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
b=np.random.random((3,4))
print(b)

[[0.26670549 0.59309646 0.8358066  0.17515498]
 [0.88476557 0.94902914 0.29998808 0.27741117]
 [0.00462525 0.60348607 0.2706961  0.23548712]]


In [ ]:
#random values array

In [ ]:
c=np.random.randint(10,100,(3,5))
print(c)

[[93 91 19 55 39]
 [21 13 33 32 43]
 [61 40 58 44 86]]


In [ ]:
#array of evenly spaced values


In [ ]:
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
#convert list to a numpy array
list2=[10,20,20,20,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)

[[27 36 21 49 77]
 [49 58 35 18 13]
 [50 83 66 21 77]
 [12 56 48 37 68]
 [26 83 55 74 46]]


In [ ]:
print(c.shape)

(5, 5)


In [ ]:
#number of dimensions
print(c.ndim)

2


In [ ]:
#number of elements in an array
print(c.size)

25


In [ ]:
#checking the data type of the values in the array
print(c.dtype)

int64


In [ ]:
list1= [1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)
print(a-b)

[[8 5 4]
 [7 6 7]
 [9 8 0]]
[[10 12 10]
 [11 18 14]
 [14 17 10]]
[[18 17 14]
 [18 24 21]
 [23 25 10]]
[[ -2  -7  -6]
 [ -4 -12  -7]
 [ -5  -9 -10]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[18 17 14]
 [18 24 21]
 [23 25 10]]
[[ -2  -7  -6]
 [ -4 -12  -7]
 [ -5  -9 -10]]
[[ 80  60  40]
 [ 77 108  98]
 [126 136   0]]
[[0.8        0.41666667 0.4       ]
 [0.63636364 0.33333333 0.5       ]
 [0.64285714 0.47058824 0.        ]]


ARRAY Manupulation

In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 7 7]
 [2 0 8]]
(2, 3)


In [ ]:
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[4 2]
 [7 0]
 [7 8]]
(3, 2)


In [ ]:
trans2= array.T
print(trans2)

[[4 2]
 [7 0]
 [7 8]]


In [ ]:
print(trans2.shape)

(3, 2)


In [ ]:
#reshaping array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 2 0]
 [9 5 9]]
(2, 3)


In [ ]:
b=a.reshape(3,2)
print(b)

[[0 2]
 [0 9]
 [5 9]]
